- id: hjord_low_battery
  alias: Hjord's batteri under 15%
  trigger:
    platform: template
    value_template: "{{ states.sensor.hjord_battery | int < 15 }}"
  action:
    service: script.test_pushbullet