#  _  _                   _          _    _            _      ___           __ _      
# | || |___ _ __  ___    /_\   _____(_)__| |_ __ _ _ _| |_   / __|___ _ _  / _(_)__ _ 
# | __ / _ \ '  \/ -_)  / _ \ (_-<_-< (_-<  _/ _` | ' \  _| | (__/ _ \ ' \|  _| / _` |
# |_||_\___/_|_|_\___| /_/ \_\/__/__/_/__/\__\__,_|_||_\__|  \___\___/_||_|_| |_\__, |
#                                                                               |___/ 
# http://patorjk.com/software/taag/#p=display&f=Small&t=Hass.io%0A                                                                                              |___/ 

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 21

  unit_system: metric
  time_zone: Europe/Copenhagen
  # Customization file
  customize: !include customize.yaml


#  ___           _    _        _ 
# | __|_ _  __ _| |__| |___ __| |
# | _|| ' \/ _` | '_ \ / -_) _` |
# |___|_||_\__,_|_.__/_\___\__,_|

frontend: # Enables the frontend
config: # Enables configuration UI

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery: # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # Track the sun

# Text to speech
tts:
  - platform: google

#  ___  _  _   ___  _    _   _  ___   ___  ___ 
# |_ _|| \| | / __|| |  | | | ||   \ | __|/ __|
#  | | | .` || (__ | |__| |_| || |) || _| \__ \
# |___||_|\_| \___||____|\___/ |___/ |___||___/

group: !include_dir_merge_named groups/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_list sensors/

#  _____ _                   _         __  __    
# |_   _| |_  ___ _ __    __| |_ _  _ / _|/ _|___
#   | | | ' \/ -_) '  \  (_-<  _| || |  _|  _(_-<
#   |_| |_||_\___|_|_|_| /__/\__|\_,_|_| |_| /__/

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

light:
# Example configuration.yaml entry
  - platform: flux_led
    devices:
      192.168.1.11:
        name: flux_strip  
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 70
    icon: mdi:castle
  - name: Work
    latitude: !secret cwork_latitude
    longitude: !secret cwork_longitude
    radius: 150  
    icon: mdi:school
 #__  __        _ _        ___ _                      
 #|  \/  |___ __| (_)__ _  | _ \ |__ _ _  _ ___ _ _ ___
 #| |\/| / -_) _` | / _` | |  _/ / _` | || / -_) '_(_-<
 #|_|  |_\___\__,_|_\__,_| |_| |_\__,_|\_, \___|_| /__/
 #                                     |__/            
media_player:
  - platform: kodi
    host: 192.168.1.7
    name: Kodi Stue
  - platform: kodi
    host: 192.168.1.5
    name: Kodi Soveværelse
  - platform: cast #Audio
    host: 192.168.1.8
  - platform: cast #Old
    host: 192.168.1.9
  - platform: cast #TV
    host: 192.168.1.7      
