#  _  _                   _          _    _            _      ___           __ _      
# | || |___ _ __  ___    /_\   _____(_)__| |_ __ _ _ _| |_   / __|___ _ _  / _(_)__ _ 
# | __ / _ \ '  \/ -_)  / _ \ (_-<_-< (_-<  _/ _` | ' \  _| | (__/ _ \ ' \|  _| / _` |
# |_||_\___/_|_|_\___| /_/ \_\/__/__/_/__/\__\__,_|_||_\__|  \___\___/_||_|_| |_\__, |
#                                                                               |___/ 
# http://patorjk.com/software/taag/#p=display&f=Small&t=Hass.io%0A                                                                                              |___/ 

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 21

  unit_system: metric
  time_zone: Europe/Copenhagen
  # Customization file
  customize: !include customize.yaml


#  ___           _    _        _ 
# | __|_ _  __ _| |__| |___ __| |
# | _|| ' \/ _` | '_ \ / -_) _` |
# |___|_||_\__,_|_.__/_\___\__,_|

frontend: # Enables the frontend
config: # Enables configuration UI

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery: # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # Track the sun

sensor:
  - platform: yr # Weather prediction
  #- platform: cpuspeed broken in hass.io?
    name: Pi CPU
  - platform: netdata
    host: 192.168.1.3
    port: 19999
    resources:
      - 'memory_free'
      - 'memory_used'
      - 'memory_cached'
      - 'memory_buffers'
      - 'swap_free'
      - 'swap_used'
      - 'processes_running'
      - 'processes_blocked'
      - 'system_load'
      - 'system_io_in'
      - 'system_io_out'
      - 'ipv4_in'
      - 'ipv4_out'
      - 'disk_free'
      - 'cpu_iowait'
      - 'cpu_user'
      - 'cpu_system'
      - 'cpu_softirq'
      - 'cpu_guest'
      - 'uptime'
      #- 'packets_received' Netdata does not work with one of these enabled
      #- 'packets_sent'
      #- 'connections'
  - platform: glances
    host: 192.168.1.3
    port: 64646
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
      - 'cpu_temp'

# Text to speech
tts:
  - platform: google

#  ___  _  _   ___  _    _   _  ___   ___  ___ 
# |_ _|| \| | / __|| |  | | | ||   \ | __|/ __|
#  | | | .` || (__ | |__| |_| || |) || _| \__ \
# |___||_|\_| \___||____|\___/ |___/ |___||___/

group: !include_dir_merge_named groups/
automation: !include automations.yaml
script: !include scripts.yaml

#  _____ _                   _         __  __    
# |_   _| |_  ___ _ __    __| |_ _  _ / _|/ _|___
#   | | | ' \/ -_) '  \  (_-<  _| || |  _|  _(_-<
#   |_| |_||_\___|_|_|_| /__/\__|\_,_|_| |_| /__/

mqtt:
  broker: core-mosquitto
  username: Hjord
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks



light:
# Example configuration.yaml entry
  - platform: flux_led
    devices:
      192.168.1.11:
        name: flux_strip  
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:castle
  - name: Claudia Work
    latitude: !secret cwork_latitude
    longitude: !secret cwork_longitude
    radius: 150  
    icon: mdi:school
 #__  __        _ _        ___ _                      
 #|  \/  |___ __| (_)__ _  | _ \ |__ _ _  _ ___ _ _ ___
 #| |\/| / -_) _` | / _` | |  _/ / _` | || / -_) '_(_-<
 #|_|  |_\___\__,_|_\__,_| |_| |_\__,_|\_, \___|_| /__/
 #                                     |__/            
media_player:
  - platform: kodi
    host: 192.168.1.7
    name: Kodi Stue
  - platform: kodi
    host: 192.168.1.5
    name: Kodi Soveværelse
  - platform: cast #Audio
    host: 192.168.1.8
  - platform: cast #Old
    host: 192.168.1.9
  - platform: cast #TV
    host: 192.168.1.7      
