#  __  __ _          ___                          
# |  \/  (_)___ __  / __| ___ _ _  ___ ___ _ _ ___
# | |\/| | (_-</ _| \__ \/ -_) ' \(_-</ _ \ '_(_-<
# |_|  |_|_/__/\__| |___/\___|_||_/__/\___/_| /__/
                                                 

- platform: yr # Weather prediction


- platform: mqtt
  state_topic: "owntracks/Hjord/Moto"
  name: "Hjord battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'