#  __  __ _          ___                          
# |  \/  (_)___ __  / __| ___ _ _  ___ ___ _ _ ___
# | |\/| | (_-</ _| \__ \/ -_) ' \(_-</ _ \ '_(_-<
# |_|  |_|_/__/\__| |___/\___|_||_/__/\___/_| /__/
                                                 

- platform: yr # Weather prediction

- platform: lastfm
  api_key: !secret lastfm_api
  users:
    - !secret lastfm_user

- platform: command_line
  name: Bad Login Counter
  command: grep -c 'Login attempt' /config/home-assistant.log


# PHONE BATTERIES

- platform: mqtt
  state_topic: "owntracks/Hjord/Moto"
  name: "Hjord battery"
  unit_of_measurement: "%"
  value_template: > 
    {% if value_json.batt %}
      {{ value_json.batt }}
    {% else %}
      {{ states('sensor.hjord_battery') }}
    {% endif %}    
  
- platform: mqtt
  state_topic: "owntracks/Chriss/Nexus"
  name: "Chriss battery"
  unit_of_measurement: "%"
  value_template: >
    {% if value_json.batt %}
      {{ value_json.batt }}
    {% else %}
      {{ states('sensor.chriss_battery') }}
    {% endif %} 
